// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:
// https://nextjs.org/learn/dashboard-app/fetching-data
//Dados iniciais
//Dados
//Tabela Cliente
const cliente = [
  {
    cod: 1001,
    nome: 'Giulia B',
  },
  {
    cod: 1002,
    nome: 'Amanda Mouro',
  },
  {
    cod: 1003,
    nome: 'Bernardo Gomes',
  },
  {
    cod: 1004,
    nome: 'Coraline Jones',
  },
  {
    cod: 1005,
    nome: 'Doris Will',
  },
  {
    cod: 1006,
    nome: 'Ernestina Sol',
  },
  {
    cod: 1007,
    nome: 'Fabio dos Santos',
  },
  {
    cod: 1008,
    nome: 'Helio Rich',
  },
];

//Tabela Estabelecimento
const estabelecimento = [
  {
    cod: 2001,
    nome: 'Bistro',
  },
  {
      cod: 2002,
      nome: 'Lanchonete e Restaurante',
  },
  {
      cod: 2003,
      nome: 'Cafeteria',
  },
];

//Tabela Item

//Estabelecimento 2001 - bebida
const item = [
  {
    cod: '001',    
    nome: 'Café Coado',
    preco: 3.50,
    tipo: 'Bebida',
    descricao: 'Bebida quente.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '002',  
    nome: 'Café com Leite',
    preco: 5.00,
    tipo: 'Bebida',
    descricao: 'Bebida quente.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '003',    
    nome: 'Suco de Laranja',
    preco: 10.00,
    tipo: 'Bebida',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '004',    
    nome: 'Suco de Limão',
    preco: 10.00,
    tipo: 'Bebida',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '005',    
    nome: 'Suco de Abacaxi',
    preco: 10.00,
    tipo: 'Bebida',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '006',    
    nome: 'Suco de Maracujá',
    preco: 10.00,
    tipo: 'Bebida',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '007',    
    nome: 'Suco de Frutas Vermelhas',
    preco: 12.00,
    tipo: 'Bebida',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '008',    
    nome: 'Morango com Leite',
    preco: 14.00,
    tipo: 'Bebida',
    descricao: 'Bebida gelada.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '009',    
    nome: 'Iogurte Batido',
    preco: 10.00,
    tipo: 'Bebida',
    descricao: 'Bebida gelada.',
    cod_estabelecimento: estabelecimento[0].cod,
  },


  //Estabelecimento 2002 - bebida
  {
      cod: '010',    
      nome: 'Expresso com Nutella',
      preco: 10.00,
      tipo: 'Bebida',
      descricao: '120 ml. café, leite integral, creme de avelã - nutella e cacau em pó.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '011',    
      nome: 'Moka',
      preco: 15.50,
      tipo: 'Bebida',
      descricao: '240 ml. leite integral, café, cobertura de chocolate, açúcar, cacau em pó, água e sal.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '012',    
      nome: 'Café Coado',
      preco: 7.00,
      tipo: 'Bebida',
      descricao: '200 ml.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '013',    
      nome: 'Expresso com Chantilly',
      preco: 9.00,
      tipo: 'Bebida',
      descricao: '210 ml. café e chantilly.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '014',    
      nome: 'Expresso Grande com Leite',
      preco: 11.00,
      tipo: 'Bebida',
      descricao: '180 ml. leite integral e café.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '015',    
      nome: 'Expresso Grande',
      preco: 11.50,
      tipo: 'Bebida',
      descricao: '180 ml. café.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '016',    
      nome: 'Chocolate Cremoso com Borda',
      preco: 12.00,
      tipo: 'Bebida',
      descricao: '120 ml. leite integral, chocolate cremoso, amido de milho, chocolate ao leite em gotas e açúcar.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '017',    
      nome: 'Chocolate Quente',
      preco: 12.00,
      tipo: 'Bebida',
      descricao: '120 ml. leite integral, chocolate em pó 33%, açúcar, cacau em pó e aromatizante.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '018',    
      nome: 'Banoffee',
      preco: 14.00,
      tipo: 'Bebida',
      descricao: '240 ml. leite integral, banana, chocolate belga em gotas, açúcar, aroma natural de baunilha e doce de leite.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '019',    
      nome: 'Chocolate Gelado',
      preco: 12.00,
      tipo: 'Bebida',
      descricao: '300 ml. leite integral, água, chocolate em pó 33%, açúcar, cacau em pó e aromatizante.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '020',    
      nome: 'Cappuccino Cremoso',
      preco: 15.00,
      tipo: 'Bebida',
      descricao: '120 ml. leite integral, cappuccino light, leitelho, aromatizante, café solúvel, cacau em pó, canela em pó e sal.',
      cod_estabelecimento: estabelecimento[1].cod,
  },


  //Estabelecimento 2003 - bebida
  {
    cod: '030',    
    nome: 'Água Mineral',
    preco: 5.30,
    tipo: 'Bebida',
    descricao: 'Garrafa.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '031',    
    nome: 'Café Expresso',
    preco: 7.30,
    tipo: 'Bebida',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '032',    
    nome: 'Café com Chantilly',
    preco: 11.10,
    tipo: 'Bebida',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '033',    
    nome: 'Chocolate Quente',
    preco: 11.00,
    tipo: 'Bebida',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '034',    
    nome: 'Cappuccino',
    preco: 11.80,
    tipo: 'Bebida',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '035',    
    nome: 'Chás Quentes',
    preco: 8.00,
    tipo: 'Bebida',
    descricao: 'Vários sabores.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '036',    
    nome: 'Iogurte',
    preco: 10.00,
    tipo: 'Bebida',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '037',    
    nome: 'MilkShake',
    preco: 32.00,
    tipo: 'Bebida',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '038',    
    nome: 'Refrigerante',
    preco: 7.90,
    tipo: 'Bebida',
    descricao: 'Lata.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '039',    
    nome: 'Suco de Laranja Natural',
    preco: 13.60,
    tipo: 'Bebida',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '040',    
    nome: 'Suco Natural',
    preco: 14.60,
    tipo: 'Bebida',
    descricao: 'Abacaxi, melancia, melão, mamão e limão.',
    cod_estabelecimento: estabelecimento[2].cod,
  },



  //Estabelecimento 2001 - lanche
  {
    cod: '101',    
    nome: 'Pão na Chapa',
    preco: 4.50,
    tipo: 'Lanche',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '102',    
    nome: 'Pão com Ovo',
    preco: 5.00,
    tipo: 'Lanche',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '103',    
    nome: 'Queijo Quente',
    preco: 5.00,
    tipo: 'Lanche',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '104',    
    nome: 'Misto Quente',
    preco: 14.00,
    tipo: 'Lanche',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '105',    
    nome: 'Seladinho de Requeijão',
    preco: 10.00,
    tipo: 'Lanche',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '106',    
    nome: 'Wrap de Atum',
    preco: 15.00,
    tipo: 'Lanche',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '107',    
    nome: 'Wrap de Frango',
    preco: 15.00,
    tipo: 'Lanche',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '108',    
    nome: 'Lanche Natural na Ciabata',
    preco: 15.00,
    tipo: 'Lanche',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '109',    
    nome: 'Carne Louca na Ciabata',
    preco: 22.00,
    tipo: 'Lanche',
    descricao: 'Carne temperada desfiada, mussarela e fritas.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '110',    
    nome: '(Filé) Frango com Queijo na Ciabata',
    preco: 20.00,
    tipo: 'Lanche',
    descricao: 'Mussarela e fritas.',
    cod_estabelecimento: estabelecimento[0].cod,
  },


  //Estabelecimento 2002 - lanche
  {
      cod: '120',    
      nome: 'Mini Sanduíche de Calabresa',
      preco: 25.00,
      tipo: 'Lanche',
      descricao: '180g. 1 unidade. pão de batata, calabresa, requeijão, açúcar, margarina, ovo, fermento biológico, água, sal, orégano e queijo prato.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '121',    
      nome: 'Mini Sanduíche de Frango com Requeijão',
      preco: 25.00,
      tipo: 'Lanche',
      descricao: '180g. 1 unidade. pão de batata, frango, requeijão, açúcar, margarina, ovos, cebola, água, fermento biológico, óleo de soja, caldo de galinha, alho, gergelim e queijo prato.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '122',    
      nome: 'Mini Sanduíche de Requeijão',
      preco: 25.00,
      tipo: 'Lanche',
      descricao: '195g. 1 unidade. pão de batata, requeijão, gordura vegetal, açúcar, ovo, queijo prato, tomate e orégano.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '123',    
      nome: 'Baguete com Parmesão',
      preco: 27.00,
      tipo: 'Lanche',
      descricao: '130g. 1 unidade. pão francês, margarina, queijo parmesão ralado, queijo prato, cheddar cremoso, catupiry, tomate seco, orégano e requeijão catupiry.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '124',    
      nome: 'Hot Dog',
      preco: 17.00,
      tipo: 'Lanche',
      descricao: '180g. 1 unidade. pão francês, margarina, queijo parmesão ralado, salsicha, queijo prato e requeijão catupiry.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '125',    
      nome: 'Misto Quente',
      preco: 12.00,
      tipo: 'Lanche',
      descricao: '172g. 1 unidade. pão francês, margarina, queijo parmesão ralado, queijo prato, tomate, requeijão catupiry, presunto e orégano.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '126',    
      nome: 'Sanduíche de Peito de Peru com Queijo.',
      preco: 16.00,
      tipo: 'Lanche',
      descricao: '170g. 1 unidade. pão francês, margarina, queijo parmesão ralado, queijo prato, peito de peru e requeijão catupiry.',
      cod_estabelecimento: estabelecimento[1].cod,
  },


//Estabelecimento 2003 - lanche
  {
      cod: '130',    
      nome: 'Sanduíche Natural Atum',
      preco: 31.90,
      tipo: 'Lanche',
      descricao: 'Pão de forma integral, atum em conserva, maionese, cebola e salsinha.',
      cod_estabelecimento: estabelecimento[2].cod,
  },
  {
      cod: '131',    
      nome: 'Sanduíche Natural Peito de Peru',
      preco: 31.90,
      tipo: 'Lanche',
      descricao: 'Pão de forma integral, peito de peru, pasta de ricota com hortelã, tomate seco e rúcula.',
      cod_estabelecimento: estabelecimento[2].cod,
  },
  {
      cod: '132',    
      nome: 'Sanduíche Natural Ricota',
      preco: 31.90,
      tipo: 'Lanche',
      descricao: 'Pão de forma integral, ricota, iogurte natural, uvas-passas e cenoura ralada.',
      cod_estabelecimento: estabelecimento[2].cod,
  },
  {
      cod: '133',    
      nome: 'Sanduíche Natural Rosbife',
      preco: 31.90,
      tipo: 'Lanche',
      descricao: 'Pão de forma integral, rosbife caseiro, mostarda, mussarela de búfala, orégano e salsinha.',
      cod_estabelecimento: estabelecimento[2].cod,
  },
  {
      cod: '134',    
      nome: 'Sanduíche Natural Salpicao de Frango',
      preco: 31.90,
      tipo: 'Lanche',
      descricao: 'Pão de forma integral, frango cozido desfiado, salsão, pimentões verdes e vermelhos, cebola, maionese e alface.',
      cod_estabelecimento: estabelecimento[2].cod,
  },
  {
      cod: '135',    
      nome: 'Beirute Simples',
      preco: 52.10,
      tipo: 'Lanche',
      descricao: 'Pão sírio, rosbife caseiro, queijo, alface, tomate e maionese especial.',
      cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '136',    
    nome: 'Beirute Especial',
    preco: 55.30,
    tipo: 'Lanche',
    descricao: 'Pão sírio, rosbife caseiro, presunto, queijo, ovo, bacon, alface, tomate e maionese especial.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '137',    
    nome: 'Beirute Filé de Frango',
    preco: 55.30,
    tipo: 'Lanche',
    descricao: 'Pão sírio, filé de frango, presunto, queijo, ovo, bacon, alface, tomate e maionese especial.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '138',    
    nome: 'Beirute Filé Mignon',
    preco: 65.10,
    tipo: 'Lanche',
    descricao: 'Pão sírio, filé mignon, presunto, queijo, ovo, bacon, alface, tomate e maionese especial.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '139',    
    nome: 'Cheeseburguer',
    preco: 26.40,
    tipo: 'Lanche',
    descricao: 'Simples.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '140',    
    nome: 'Cheeseburguer Bacon',
    preco: 29.60,
    tipo: 'Lanche',
    descricao: 'Bacon.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '141',    
    nome: 'Cheeseburguer Egg',
    preco: 29.00,
    tipo: 'Lanche',
    descricao: 'Ovo.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '142',    
    nome: 'Queijo Quente Ciabatta',
    preco: 26.90,
    tipo: 'Lanche',
    descricao: 'Com mussarela, parmesão, gorgonzola, tomate cereja e pesto de manjericão.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '143',    
    nome: 'Queijo Quente Natural',
    preco: 26.50,
    tipo: 'Lanche',
    descricao: 'Com crosta de parmesão recheado com mussarela e gorgonzola.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '144',    
    nome: 'Queijo Quente Australiano',
    preco: 26.90,
    tipo: 'Lanche',
    descricao: 'Com cheddar, queijo prato e bacon.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '145',    
    nome: 'Sanduíche X-Tudo',
    preco: 46.20,
    tipo: 'Lanche',
    descricao: 'Hambúrguer, queijo, bacon, ovo, salada, presunto e maionese especial.',
    cod_estabelecimento: estabelecimento[2].cod,
  },

  //Estabelecimento 2002 - salgados
  {
      cod: '150',    
      nome: 'Pão de Queijo',
      preco: 12.00,
      tipo: 'Salgados',
      descricao: '156g. 12 unidades. polvilho azedo, queijos, ovos, margarina, óleo de soja, soro de leite e sal.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '151',    
      nome: 'Folhado de Frango',
      preco: 17.00,
      tipo: 'Salgados',
      descricao: '100g. 1 unidade. frango, cebola, azeitona, alho frito, caldo de galinha e orégano.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '152',    
      nome: 'Folhado Quatro Queijos',
      preco: 17.00,
      tipo: 'Salgados',
      descricao: '125g. 1 unidade. queijo prato, queijo tipo mussarela, creme de ricota, queijo tipo provolone e queijo parmesão.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '153',    
      nome: 'Pizza Folhada de Calabresa',
      preco: 16.00,
      tipo: 'Salgados',
      descricao: '120g. 1 unidade. calabresa, apresuntado, requeijão e cebola.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '154',    
      nome: 'Pizza Folhada de Frango com Requeijão',
      preco: 16.00,
      tipo: 'Salgados',
      descricao: '120g. 1 unidade. frango, requeijão, cebola, alho, salsa e pimenta do reino.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '155',    
      nome: 'Empada de Palmito',
      preco: 15.00,
      tipo: 'Salgados',
      descricao: '90g. 1 unidade. palmito, creme de cebola e ovo.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '156',    
      nome: 'Coxinha de Frango com Requeijão',
      preco: 15.00,
      tipo: 'Salgados',
      descricao: '80g. 1 unidade. frango desfiado, requeijão, batata em flocos, margarina, farinha de rosca, cebola, alho, salsa, sal e ovos.',
      cod_estabelecimento: estabelecimento[1].cod,
  },


  //Estabelecimento 2003 - salgado
  {
    cod: '170',    
    nome: 'Bolinho de Carne',
    preco: 10.50,
    tipo: 'Salgados',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '171',    
    nome: 'Croquete',
    preco: 10.50,
    tipo: 'Salgados',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '172',    
    nome: 'Risolis',
    preco: 10.50,
    tipo: 'Salgados',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '173',    
    nome: 'Coxinha',
    preco: 10.50,
    tipo: 'Salgados',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '174',    
    nome: 'Empadinha',
    preco: 10.50,
    tipo: 'Salgados',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '175',    
    nome: 'Pão de Queijo',
    preco: 10.00,
    tipo: 'Salgados',
    descricao: '1 unidade.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '176',    
    nome: 'Batata Frita',
    preco: 26.90,
    tipo: 'Salgados',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  

  
//Estabelecimento 2001 - tapioca
  {
    cod: '201',    
    nome: 'Pizza',
    preco: 16.00,
    tipo: 'Tapioca',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '202',    
    nome: '2 Queijos',
    preco: 17.00,
    tipo: 'Tapioca',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '203',    
    nome: 'Atum com Tomate',
    preco: 15.00,
    tipo: 'Tapioca',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '204',    
    nome: 'Frango com Queijo',
    preco: 17.00,
    tipo: 'Tapioca',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '205',    
    nome: 'Nutella',
    preco: 18.00,
    tipo: 'Tapioca',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },


  //Estabelecimento 2003 - tapioca
  {
    cod: '220',    
    nome: 'Peito de Peru',
    preco: 25.70,
    tipo: 'Tapioca',
    descricao: 'Salgada - Peito de peru, queijo branco, tomate, azeite e orégano.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '220',    
    nome: 'Presunto',
    preco: 22.70,
    tipo: 'Tapioca',
    descricao: 'Salgada - Presunto, mussarela, tomate, azeite e orégano.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '220',    
    nome: 'Berinjela',
    preco: 22.70,
    tipo: 'Tapioca',
    descricao: 'Salgada - Caponata de berinjela.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '220',    
    nome: 'Coco com Leite Condensado',
    preco: 22.70,
    tipo: 'Tapioca',
    descricao: 'Doce - Coco com leite condensado.',
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: '220',    
    nome: 'Nutella',
    preco: 22.70,
    tipo: 'Tapioca',
    descricao: 'Doce - Nutella.',
    cod_estabelecimento: estabelecimento[2].cod,
  },


  //Estabelecimento 2001 - prato executivo
  {
    cod: '301',    
    nome: 'Polpetone à Parmegiana',
    preco: 40.50,
    tipo: 'Prato Executivo',
    descricao: 'Fettuccine ao molho sugo.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '302',    
    nome: 'Filé de Carne Acebolado',
    preco: 37.00,
    tipo: 'Prato Executivo',
    descricao: 'Arroz, feijão e saladinha.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '303',    
    nome: 'Filé de Carne à Parmegiana',
    preco: 40.50,
    tipo: 'Prato Executivo',
    descricao: 'Arroz e batatas fritas.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '304',    
    nome: 'Filé de Carne à Cavalo',
    preco: 38.50,
    tipo: 'Prato Executivo',
    descricao: 'Arroz, feijão, ovo, fritas e saladinha.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '305',    
    nome: 'Filé de Carne à Milanesa',
    preco: 39.00,
    tipo: 'Prato Executivo',
    descricao: 'Arroz, feijão e fritas.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '306',    
    nome: 'Filé de Frango à Milanesa',
    preco: 36.50,
    tipo: 'Prato Executivo',
    descricao: 'Arroz, feijão e fritas.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '307',    
    nome: 'Filé de Frango com Legumes',
    preco: 32.00,
    tipo: 'Prato Executivo',
    descricao: 'Arroz integral, legumes na manteiga e saladinha.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '308',    
    nome: 'Filé de Frango à Cavalo',
    preco: 35.50,
    tipo: 'Prato Executivo',
    descricao: 'Arroz, feijão, ovo, fritas e saladinha.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '309',    
    nome: 'Filé de Frango à Parmegiana',
    preco: 38.50,
    tipo: 'Prato Executivo',
    descricao: 'Arroz e fritas.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '310',    
    nome: 'Filé de Peixe ao Molho Ervas Finas',
    preco: 40.50,
    tipo: 'Prato Executivo',
    descricao: 'Saint peter, arroz, legumes na manteiga e saladinha.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '311',    
    nome: 'Strogonoff de Carne',
    preco: 37.00,
    tipo: 'Prato Executivo',
    descricao: 'Arroz e batata palha.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '312',    
    nome: 'Strogonoff de Frango',
    preco: 33.00,
    tipo: 'Prato Executivo',
    descricao: 'Arroz e batata palha.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '313',    
    nome: 'Berinjela à Parmegiana',
    preco: 33.50,
    tipo: 'Prato Executivo',
    descricao: 'Vegetariano. arroz integral e saladinha.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '314',    
    nome: 'Omelete',
    preco: 26.00,
    tipo: 'Prato Executivo',
    descricao: 'Queijo, presunto, tomate, cebola, arroz, feijão e saladinha.',
    cod_estabelecimento: estabelecimento[0].cod,
  },


  //Estabelecimento 2002 - prato executivo
  {
      cod: '320',    
      nome: 'Canelloni de Alho Poró com Palmito',
      preco: 26.00,
      tipo: 'Prato Executivo',
      descricao: '350g. 1 unidade. molho de tomate, abobrinha, mozarela, farinha de trigo, alho poró, espinafre, ovo, alho, sal, molho bechamel e queijo mozzarella ralado.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '321',    
      nome: 'Escondidinho de Carne Seca',
      preco: 26.00,
      tipo: 'Prato Executivo',
      descricao: '350g. 1 unidade. mandioca, carne seca, tomate, creme de leite, cebola, requeijão cremoso, manteiga, leite de coco, parmesão, cheiro verde, alho, molho de pimenta e queijo mozzarella ralado.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '322',    
      nome: 'Escondidinho de Frango com Batata Doce',
      preco: 26.00,
      tipo: 'Prato Executivo',
      descricao: '350g. 1 unidade. batata doce, filé de frango, tomate, cebola, leite de coco, alho, azeite de oliva extra virgem, sal, salsa, molho de pimenta vermelha e queijo mozzarella ralado.',
      cod_estabelecimento: estabelecimento[1].cod,
  },


  //Estabelecimento 2001 - salada
  {
    cod: '401',    
    nome: 'Salada Caesar',
    preco: 33.00,
    tipo: 'Saladas',
    descricao: 'Alface americana, parmesão, crountons e filé de frango.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '402',    
    nome: 'Salada da Casa',
    preco: 34.00,
    tipo: 'Saladas',
    descricao: 'Folhas verdes, tomate cereja, cenoura, mussarela e filé de frango.',
    cod_estabelecimento: estabelecimento[0].cod,
  },

  //Estabelecimento 2001 - omelete
  {
    cod: '501',    
    nome: 'Omelete Completo',
    preco: 25.00,
    tipo: 'Omelete',
    descricao: 'Queijo, tomate, cebola e presunto.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '502',    
    nome: 'Omelete com Saladinha',
    preco: 22.00,
    tipo: 'Omelete',
    descricao: 'Queijo, tomate, cebola e presunto.',
    cod_estabelecimento: estabelecimento[0].cod,
  },

  //Estabelecimento 2001 - massa
  {
    cod: '601',    
    nome: 'Spaguetti',
    preco: 27.00,
    tipo: 'Massa',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '602',    
    nome: 'Penne',
    preco: 27.00,
    tipo: 'Massa',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '603',    
    nome: 'Fettuccine',
    preco: 28.00,
    tipo: 'Massa',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '604',    
    nome: 'Nhoque de Batata',
    preco: 31.00,
    tipo: 'Massa',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '605',    
    nome: 'Ravioli Verde de Búfala',
    preco: 42.00,
    tipo: 'Massa',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '606',    
    nome: 'Ravioli de Carne',
    preco: 40.00,
    tipo: 'Massa',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '607',    
    nome: 'Lasanha Presunto e Queijo a Bolonhesa',
    preco: 40.50,
    tipo: 'Massa',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '608',    
    nome: 'Lasanha Mussarela com Molho Branco',
    preco: 42.50,
    tipo: 'Massa',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '609',    
    nome: 'Ravioli Zucca de Abóbora',
    preco: 33.00,
    tipo: 'Massa',
    descricao: 'Vegetariano.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '621',    
    nome: 'Molho Sugo',
    preco: 0.00,
    tipo: 'Molho para Massa',
    descricao: 'Acompanhamento de massa.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '622',    
    nome: 'Molho Branco',
    preco: 0.00,
    tipo: 'Molho para Massa',
    descricao: 'Acompanhamento de massa.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '623',    
    nome: 'Molho Rosé',
    preco: 0.00,
    tipo: 'Molho para Massa',
    descricao: 'Acompanhamento de massa.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '624',    
    nome: 'Molho Bolonhesa',
    preco: 0.00,
    tipo: 'Molho para Massa',
    descricao: 'Acompanhamento de massa.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '631',    
    nome: 'Filé de Frango à Milanesa',
    preco: 12.00,
    tipo: 'Filé para Massas',
    descricao: 'Acompanhamento de massa.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '632',    
    nome: 'Filé de Frango Grelhado',
    preco: 8.00,
    tipo: 'Filé para Massas',
    descricao: 'Acompanhamento de massa.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '701',    
    nome: 'Filé de Carne à Milanesa',
    preco: 18.00,
    tipo: 'Acompanhamentos',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '702',    
    nome: 'Filé de Frango Grelhado',
    preco: 11.00,
    tipo: 'Acompanhamentos',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '703',    
    nome: 'Filé de Frango à Milanesa',
    preco: 15.00,
    tipo: 'Acompanhamentos',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '704',    
    nome: 'Feijão, Arroz, Legumes ou Saladinha',
    preco: 8.00,
    tipo: 'Acompanhamentos',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '705',    
    nome: 'Fritas',
    preco: 10.00,
    tipo: 'Acompanhamentos',
    descricao: 'Sem descrição.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '801',    
    nome: 'Strogonoff de Frango',
    preco: 25.00,
    tipo: 'Pratos Kids',
    descricao: 'Arroz e batata palha.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '802',    
    nome: 'Da Casa',
    preco: 25.00,
    tipo: 'Pratos Kids',
    descricao: 'Arroz, feijão e iscas de fraldinha.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '803',    
    nome: 'Almôndegas',
    preco: 22.00,
    tipo: 'Pratos Kids',
    descricao: 'Arroz, feijão, 02 almôndegas e saladinha.',
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: '804',    
    nome: 'Filé de Frango Grelhado',
    preco: 22.00,
    tipo: 'Pratos Kids',
    descricao: 'Arroz, feijão e fritas.',
    cod_estabelecimento: estabelecimento[0].cod,
  },

//Estabelecimento 2002 - sobremesa
  {
      cod: '900',    
      nome: 'Brownie',
      preco: 12.00,
      tipo: 'Sobremesa',
      descricao: '60g. 1 unidade. açúcar refinado, chocolate meio amargo, farinha de trigo, manteiga sem sal, margarina, cacau em pó, ovo desidratado, nozes e castanha-do-pará.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '901',    
      nome: 'Doce de Leite',
      preco: 5.00,
      tipo: 'Sobremesa',
      descricao: '30g. 1 unidade. leite e açúcar.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '902',    
      nome: 'Beijinho',
      preco: 5.00,
      tipo: 'Sobremesa',
      descricao: '40g. 1 unidade. leite condensado, coco e margarina.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '903',    
      nome: 'Bolo de Fubá',
      preco: 12.00,
      tipo: 'Sobremesa',
      descricao: 'Uma fatia.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '904',    
      nome: 'Brigadeiro',
      preco: 5.00,
      tipo: 'Sobremesa',
      descricao: '40g. 1 unidade. leite condensado, granulado sabor chocolate, chocolate em pó e margarina.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '905',    
      nome: 'Croissant de Chocolate',
      preco: 15.00,
      tipo: 'Sobremesa',
      descricao: '185g. 1 unidade. farinha de trigo, recheio de chocolate ao leite, açúcar, ovo e chocolate ao leite em gotas.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '906',    
      nome: 'Cookies de Baunilha com Gotas de Chocolate',
      preco: 7.00,
      tipo: 'Sobremesa',
      descricao: '65g. 1 unidade. açúcar cristal, farinha de trigo, gotas de chocolate meio amargo, margarina, gotas de chocolate ao leite, farinha de aveia, ovo, aroma de baunilha e chocolate ao leite em gotas.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '907',    
      nome: 'Churros',
      preco: 9.00,
      tipo: 'Sobremesa',
      descricao: '65g. 1 unidade. água, farinha de trigo, doce de leite, açúcar, margarina, farinha de milho, sal e aroma idêntico ao natural de baunilha.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  {
      cod: '908',    
      nome: 'Mini Broa de Milho',
      preco: 9.00,
      tipo: 'Sobremesa',
      descricao: '72g. 6 unidades. fubá de milho, ovos, leite, fécula, margarina, erva-doce, açúcar e sal.',
      cod_estabelecimento: estabelecimento[1].cod,
  },
  

];

//Tabela Pedidos
const pedidos= [
  {
    cod: 5001,
    datas: "22 de Abril de 2024",
    statusPedido: 'Finalizado',
    tipo_pagamento: 'Cartão de Crédito',
    valor_total: 14.50,
    cod_cliente: cliente[0].cod,
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: 5002,
    datas: "4 de Março de 2024",
    statusPedido: 'Em andamento',
    tipo_pagamento: 'PIX',
    valor_total: 17.50,
    cod_cliente: cliente[1].cod,
    cod_estabelecimento: estabelecimento[1].cod,
  },
  {
    cod: 5003,
    datas: "13 de Dezembro de 2024",
    statusPedido: 'Cancelado',
    tipo_pagamento: 'Cartão de Débito',
    valor_total: 57.50,
    cod_cliente: cliente[2].cod,
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: 5004,
    datas: "29 de Abril de 2024",
    statusPedido: 'Finalizado',
    tipo_pagamento: 'VR',
    valor_total: 30.50,
    cod_cliente: cliente[3].cod,
    cod_estabelecimento: estabelecimento[0].cod,
  },
  {
    cod: 5005,
    datas: "15 de Novembro de 2024",
    statusPedido: 'Em andamento',
    tipo_pagamento: 'VR',
    valor_total: 48.00,
    cod_cliente: cliente[4].cod,
    cod_estabelecimento: estabelecimento[1].cod,
  },
  {
    cod: 5006,
    datas: "31 de Outubro de 2024",
    statusPedido: 'Cancelado',
    tipo_pagamento: 'PIX',
    valor_total: 50.00,
    cod_cliente: cliente[5].cod,
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: 5007,
    datas: "8 de Janeiro de 2024",
    statusPedido: 'Em andamento',
    tipo_pagamento: 'VR',
    valor_total: 26.50,
    cod_cliente: cliente[6].cod,
    cod_estabelecimento: estabelecimento[2].cod,
  },
  {
    cod: 5008,
    datas: "10 de Fevereiro de 2024",
    statusPedido: 'Em andamento',
    tipo_pagamento: 'Cartão de Crédito',
    valor_total: 50.00,
    cod_cliente: cliente[7].cod,
    cod_estabelecimento: estabelecimento[0].cod,
  },
];

//Tabela Itens Pedido
const itens_pedido = [
  {
    cod_pedido: pedidos[0].cod,
    cod_item: item[9].cod,
    cod_estabelecimento: estabelecimento[0].cod,
    quantidade_item: 1,
  },
  {
    cod_pedido: pedidos[0].cod,
    cod_item: item[10].cod,
    cod_estabelecimento: estabelecimento[0].cod,
    quantidade_item: 1,
  },
  {
    cod_pedido: pedidos[0].cod,
    cod_item: item[29].cod,
    cod_estabelecimento: estabelecimento[0].cod,
    quantidade_item: 1,
  },
  {
    cod_pedido: pedidos[1].cod,
    cod_item: item[4].cod,
    cod_estabelecimento: estabelecimento[0].cod,
    quantidade_item: 1,
  },
  {
    cod_pedido: pedidos[1].cod,
    cod_item: item[104].cod,
    cod_estabelecimento: estabelecimento[0].cod,
    quantidade_item: 1,
  },
  {
    cod_pedido: pedidos[2].cod,
    cod_item: item[80].cod,
    cod_estabelecimento: estabelecimento[0].cod,
    quantidade: 1,
  },
  {
    cod_pedido: pedidos[2].cod,
    cod_item: item[43].cod,
    cod_estabelecimento: estabelecimento[0].cod,
    quantidade: 1,
  },
  {
    cod_pedido: pedidos[3].cod,
    cod_item: item[15].cod,
    cod_estabelecimento: estabelecimento[1].cod,
    quantidade: 1,
  },
  {
    cod_pedido: pedidos[3].cod,
    cod_item: item[34].cod,
    cod_estabelecimento: estabelecimento[1].cod,
    quantidade: 1,
  },
  {
    cod_pedido: pedidos[4].cod,
    cod_item: item[56].cod,
    cod_estabelecimento: estabelecimento[1].cod,
    quantidade: 1,
  },
  {
    cod_pedido: pedidos[4].cod,
    cod_item: item[19].cod,
    cod_estabelecimento: estabelecimento[1].cod,
    quantidade: 1,
  },
  {
    cod_pedido: pedidos[4].cod,
    cod_item: item[57].cod,
    cod_estabelecimento: estabelecimento[1].cod,
    quantidade: 1,
  },
  {
    cod_pedido: pedidos[4].cod,
    cod_item: item[76].cod,
    cod_estabelecimento: estabelecimento[1].cod,
    quantidade: 1,
  },
  {
    cod_pedido: pedidos[5].cod,
    cod_item: item[65].cod,
    cod_estabelecimento: estabelecimento[2].cod,
    quantidade: 1,
  },
  {
    cod_pedido: pedidos[5].cod,
    cod_item: item[68].cod,
    cod_estabelecimento: estabelecimento[2].cod,
    quantidade: 1,
  },
  {
    cod_pedido: pedidos[5].cod,
    cod_item: item[78].cod,
    cod_estabelecimento: estabelecimento[2].cod,
    quantidade: 1,
  },
  {
    cod_pedido: pedidos[6].cod,
    cod_item: item[48].cod,
    cod_estabelecimento: estabelecimento[2].cod,
    quantidade: 1,
  },
  {
    cod_pedido: pedidos[7].cod,
    cod_item: item[39].cod,
    cod_estabelecimento: estabelecimento[2].cod,
    quantidade: 1,
  },
  {
    cod_pedido: pedidos[7].cod,
    cod_item: item[3].cod,
    cod_estabelecimento: estabelecimento[2].cod,
    quantidade: 1,
  },
  {
    cod_pedido: pedidos[7].cod,
    cod_item: item[0].cod,
    cod_estabelecimento: estabelecimento[2].cod,
    quantidade: 1,
  },
  {
    cod_pedido: pedidos[7].cod,
    cod_item: item[26].cod,
    cod_estabelecimento: estabelecimento[2].cod,
    quantidade: 1,
  },
  {
    cod_pedido: pedidos[7].cod,
    cod_item: item[60].cod,
    cod_estabelecimento: estabelecimento[2].cod,
    quantidade: 1,
  },
];

module.exports = {
  cliente,
  estabelecimento,
  item,
  pedidos,
  itens_pedido,
};